BUG: Allow all appropriate links in a Family
The list of links in a Family (Poisson, Gaussian, etc.) included the
"aliased" link type instead of the primary link type, when possible.
Poisson, for example, include link.log instead of link.Log.

Using the aliased class in the family link list results in suprising
behavior like this:

```
In [1]: import statsmodels.genmod.families as F

In [2]: import statsmodels.genmod.families.links as L

In [3]: F.Poisson(link=L.log())
Out[3]: <statsmodels.genmod.families.family.Poisson at 0x111da15b0>

In [4]: F.Poisson(link=L.Log())
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-47050bb1e621> in <module>
----> 1 F.Poisson(link=L.Log())

~/Documents/old/statsmodels/statsmodels/genmod/families/family.py in __init__(self, link)
    399         if link is None:
    400             link = L.log()
--> 401         super(Poisson, self).__init__(link=link, variance=Poisson.variance)
    402
    403     def _resid_dev(self, endog, mu):

~/Documents/old/statsmodels/statsmodels/genmod/families/family.py in __init__(self, link, variance)
     83             raise TypeError(warnmssg)
     84         else:
---> 85             self.link = link
     86         self.variance = variance
     87

~/Documents/old/statsmodels/statsmodels/genmod/families/family.py in _setlink(self, link)
     64             if not validlink:
     65                 errmsg = "Invalid link for family, should be in %s. (got %s)"
---> 66                 raise ValueError(errmsg % (repr(self.links), link))
     67
     68     def _getlink(self):

ValueError: Invalid link for family, should be in [<class 'statsmodels.genmod.families.links.log'>, <class 'statsmodels.genmod.families.links.identity'>, <class 'statsmodels.genmod.families.links.sqrt'>]. (got <statsmodels.genmod.families.links.Log object at 0x111e7efa0>)
```

L.log works but L.Log doesn't, even though L.log is an simply an "alias"
of L.Log.

By changing the family link lists to use "unaliased" classes (the parent
classes of the various aliases) both L.log and L.Log work as expected.