solve bug on Ubuntu due to failed import
When using the old import statement on Ubuntu, the following error was thrown: 
ImportError: cannot import name 'factorial'